# Generated by Django 3.2.10 on 2021-12-08 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
    ]
