# Generated by Django 2.1 on 2018-08-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                (
                    'creation_timestamp',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='creation timestamp',
                    ),
                ),
                (
                    'update_timestamp',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='update timestamp',
                    ),
                ),
                (
                    'classroom',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='posts',
                        to='classrooms.Classroom',
                    ),
                ),
            ],
        ),
    ]
