# Generated by Django 4.1.3 on 2022-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('classrooms', models.ManyToManyField(related_name='courses', to='classrooms.classroom', verbose_name='classrooms')),
            ],
        ),
    ]
