# Generated by Django 4.1.3 on 2022-11-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classrooms',
        ),
    ]
