# Generated by Django 4.1.6 on 2023-04-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='is archived'),
        ),
    ]
