# Generated by Django 2.1.7 on 2019-03-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                default=1,
                max_length=254,
                unique=True,
                verbose_name='email address',
            ),
            preserve_default=False,
        ),
    ]
