# Generated by Django 2.1 on 2018-09-09 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0002_auto_20180816_1540'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(verbose_name='fecha')),
                (
                    'creation_timestamp',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='creation timestamp',
                    ),
                ),
                (
                    'update_timestamp',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='update timestamp',
                    ),
                ),
                (
                    'classroom',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='classrooms.Classroom',
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
