# Generated by Django 2.1.7 on 2019-03-12 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0003_auto_20190307_0325'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('subject', models.CharField(max_length=255, verbose_name='asunto')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('is_sent', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='creation timestamp',
                )),
                ('update_timestamp', models.DateTimeField(
                    auto_now=True,
                    verbose_name='update timestamp',
                )),
                ('classroom', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='questions',
                    to='classrooms.Classroom',
                )),
                ('creator', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='questions',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ('creation_timestamp',),
            },
        ),
    ]
