# Generated by Django 2.1.7 on 2019-03-12 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('message', models.TextField(verbose_name='mensaje')),
                ('is_sent', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='creation timestamp',
                )),
                ('update_timestamp', models.DateTimeField(
                    auto_now=True,
                    verbose_name='update timestamp',
                )),
                ('creator', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='answers',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='answers',
                    to='questions.Question',
                )),
            ],
            options={
                'ordering': ('creation_timestamp',),
            },
        ),
    ]
