# Generated by Django 3.2.5 on 2021-07-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('run', models.IntegerField(null=True, unique=True, verbose_name='RUN')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='persons.Person')),
            ],
        ),
    ]
