# Generated by Django 3.1.8 on 2021-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='persons.Person'),
        ),
    ]
