# Generated by Django 3.1.8 on 2021-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='run',
            field=models.CharField(max_length=150, unique=True, verbose_name='RUN'),
        ),
    ]
