# Generated by Django 3.1.8 on 2021-04-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20210424_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='run',
            field=models.IntegerField(null=True, unique=True, verbose_name='RUN'),
        ),
    ]
