# Generated by Django 3.2.5 on 2021-07-20 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_remove_classroom_head_teacher'),
        ('persons', '0003_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='classrooms.classroom'),
            preserve_default=False,
        ),
    ]
