# Generated by Django 3.2.10 on 2021-12-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_remove_classroom_students'),
        ('persons', '0004_person_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='run',
        ),
        migrations.AlterField(
            model_name='person',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classrooms.classroom'),
        ),
    ]
