# Generated by Django 3.2.5 on 2021-07-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('classrooms', models.ManyToManyField(related_name='courses', to='classrooms.Classroom', verbose_name='classrooms')),
            ],
        ),
    ]
