# Generated by Django 3.2 on 2021-05-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_alter_classroom_id'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classrooms',
            field=models.ManyToManyField(related_name='courses', to='classrooms.Classroom', verbose_name='classrooms'),
        ),
    ]
