# Generated by Django 4.1.6 on 2023-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'mensaje', 'verbose_name_plural': 'mensajes'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
