# Generated by Django 2.1.7 on 2019-03-07 03:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20180816_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(
                blank=True,
                related_name='classrooms',
                to=settings.AUTH_USER_MODEL,
                verbose_name='students',
            ),
        ),
    ]
