# Generated by Django 3.2 on 2021-05-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_alter_person_id'),
        ('classrooms', '0003_alter_classroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='head_classrooms', to='persons.person', verbose_name='teacher'),
            preserve_default=False,
        ),
    ]
