# Generated by Django 3.2 on 2021-05-02 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_alter_person_id'),
        ('classrooms', '0004_classroom_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classroom',
            name='head_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leaderships', to='persons.person', verbose_name='head teacher'),
            preserve_default=False,
        ),
    ]
