# Generated by Django 3.2.5 on 2021-07-09 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_run'),
        ('evaluations', '0003_auto_20210709_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivered', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='delivery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='persons.person'),
        ),
    ]
