# Generated by Django 3.2.10 on 2021-12-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_alternative_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
    ]
