# Generated by Django 4.1.3 on 2023-01-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='tax_identifier',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='tax_identifier',
            new_name='run',
        ),
    ]
