# Generated by Django 4.1.3 on 2022-11-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_classrooms'),
        ('persons', '0002_parent_student_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course'),
            preserve_default=False,
        ),
    ]
