# Generated by Django 4.1.3 on 2023-01-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('persons', '0002_rename_tax_identifier_parent_run_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'apoderado', 'verbose_name_plural': 'apoderados'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'estudiante', 'verbose_name_plural': 'estudiantes'},
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='apellidos'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('course', 'run')},
        ),
    ]
