# Generated by Django 4.1.6 on 2023-03-06 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='update timestamp')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='courses.course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
